### ISSUE TITLE
Swiftのバージョンの違いで関係の無いエラーが発生する

### ISSUE THREAD

**Issue by ir77** [aritaku/TryErrors#1]
どうしましょう。

**Comment by ir77** [comment]
errorSamples105/errorSamples105/ViewController.swift:21:77: Could not find an overload for 'init' that accepts the supplied arguments

**Comment by aritaku** [comment]
確かに。全然考えてなかったっす。

**Comment by ir77** [comment]
研修生のXcodeのバージョンって統一してるん？

**Comment by aritaku** [comment]
きちんとした確認は取れてないです。前回見た感じでは全員が6.2以上だったような。。。

**Comment by ir77** [comment]
いや、うちがXcode7を使ってるだけか。
たぶん気にしないでいいかも。

**Comment by aritaku** [comment]
でも、うっちーさんがグループにXcode7にアップデートしておきましょうって言ってるからそういう人も出てくるかもしれないですね。

**Comment by ir77** [comment]
かもね。
ちなみにあれはアップデートしようじゃなくて、アップデート版もダウンロードしておきましょうって意味ね。

**Comment by aritaku** [comment]
あ、なるほど。
