### ISSUE TITLE
* segueのIdentiferが違う

### ISSUE THREAD

**Issue by ir77** [aritaku/TryErrors#2]
これって元々toSecondViewやんね

**Comment by aritaku** [comment]
です！

**Comment by ir77** [comment]
toSecondViewでコードもstoryboradも設定されてない？

**Comment by aritaku** [comment]
secondのsをコードの方で一箇所小文字にしてあります。もっと分かりやすい方がいいですかね？

**Comment by ir77** [comment]
あーそういうことかwすまんw
うん、分かりやすいほうがいいと思う。ここで判断したいのは細かい誤字チェックの話ではないから

**Comment by aritaku** [comment]
変えときます！
