### ISSUE TITLE
errorSamples101が見れない

### ISSUE THREAD

**Issue by ha1f** [aritaku/TryErrors#5]
errorSamples101がおそらくgitのsubmoduleになっているので、修正してaddし直す必要有

**Comment by aritaku** [comment]
覚えてないけど、そもそもerrorSample101を作っていなかった可能性。
作ってaddします。

**Comment by ha1f** [comment]
なければカウント限定で

https://github.com/ha1fha1f/correctCount作ったのでこれの
code/spelでいいかもしれません

**Comment by aritaku** [comment]
指摘通りsubmodule関連でミスってたので修正しましたー
